pluginManagement {
    repositories {
        google {
            content {
                includeGroupByRegex("com\\.android.*")
                includeGroupByRegex("com\\.google.*")
                includeGroupByRegex("androidx.*")
            }
        }
        mavenCentral()
        gradlePluginPortal()
    }
}

// Load the secret.properties file
def secretPropertiesFile = new File(rootDir, "secrets.properties") // Use new File() for settings.gradle
def secretProperties = new Properties()

if (secretPropertiesFile.exists()) {
    secretProperties.load(new FileInputStream(secretPropertiesFile))
}

dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google()
        mavenCentral()
        maven {
            url = uri("https://api.mapbox.com/downloads/v2/releases/maven")
            credentials.username = "mapbox"
            credentials.password = secretProperties['MAP_BOX_API_KEY']
            authentication { basic(BasicAuthentication) }
        }
    }
}

rootProject.name = "Time Capsule"
include ':app'
include ':domain'
include ':data'
include ':di'
include ':util'
include ':model'
